name: vcard_example
description: Demonstrates how to use the vcard package - a dart port of vCard JS by Eric J Nesser.

dependencies:
  flutter:
    sdk: flutter
  vcard:
    path: ../
  

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
